### ISSUE TITLE
Folding eats the next prompt

### ISSUE THREAD

**Issue by elkarouh** [jdtsmith/comint-fold#1]
I defined a regex for gdb prompt
(setq gdb-prompt-regexp "^(\\(gdb\\)[[:space:]]*")
(add-hook 'gud-mode-hook (comint-fold-configure-hook 0 'gdb-prompt-regexp))

But when using it, it eats the following prompt e.g.
(gdb)break hello
bbbbbb
nnnnnn
(gdb)info break
dddd
eeee

When pressing <tab> on the line containing (gdb)break hello, i get
(gdb)....info break
dddd
eeee

**Comment by jdtsmith** [comment]
Strange.  Does comint-next-prompt move you correctly between ends of prompt?  BTW, I see that gud.el already sets comint-prompt-regexp.  

Your regex looks malformed (missing `)`, unnecessary `\(\)`, single `\` escape).  Did you try without the hook?

**Comment by elkarouh** [comment]
Yes.
It sets the cursor just after (gdb)
But the fold should comprise the next prompt. It should stop at the end of
the preceding line.
FYI, my config
(setq gdb-prompt-regexp "^(\\(gdb\\)[[:space:]]*")
(add-hook 'gud-mode-hook (comint-fold-configure-hook 0 'gdb-prompt-regexp))

Regards

**Comment by jdtsmith** [comment]
Yes to what?  I asked 2 questions.  Your regex is _still_ malformed.  Try two things:

1. Remove the gud-mode-hook, just let comint-fold figure things out itself.  Does it work?
2. If 1 doesn't work, try `(add-hook 'gud-mode-hook (comint-fold-configure-hook 0 (rx bol "(gdb)" (+ space))))`

**Comment by elkarouh** [comment]
The second option works !
many thanks !

**Comment by jdtsmith** [comment]
BTW, this should probably be `gdb-mode-hook`, since gud can run _many_ different debuggers besides gdb.
